#pragma once

/* === Normal Types === */
typedef struct t_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute t_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute;
typedef struct t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Void;
typedef struct t_IL2X_CoreLib_System_Runtime_CompilerServices_IsReadOnlyAttribute t_IL2X_CoreLib_System_Runtime_CompilerServices_IsReadOnlyAttribute;
typedef struct t_IL2X_CoreLib_IL2X_NativeExternAttribute t_IL2X_CoreLib_IL2X_NativeExternAttribute;
typedef struct t_IL2X_CoreLib_System_String t_IL2X_CoreLib_System_String;
typedef struct t_IL2X_CoreLib_IL2X_NativeStringParamAttribute t_IL2X_CoreLib_IL2X_NativeStringParamAttribute;
typedef struct t_IL2X_CoreLib_IL2X_NativeTypeAttribute t_IL2X_CoreLib_IL2X_NativeTypeAttribute;
typedef struct t_IL2X_CoreLib_System_Activator t_IL2X_CoreLib_System_Activator;
typedef struct t_IL2X_CoreLib_System_ArgumentException t_IL2X_CoreLib_System_ArgumentException;
typedef struct t_IL2X_CoreLib_System_ArgumentOutOfRangeException t_IL2X_CoreLib_System_ArgumentOutOfRangeException;
typedef struct t_IL2X_CoreLib_System_Array t_IL2X_CoreLib_System_Array;
typedef struct t_IL2X_CoreLib_System_Attribute t_IL2X_CoreLib_System_Attribute;
typedef struct t_IL2X_CoreLib_System_AttributeUsageAttribute t_IL2X_CoreLib_System_AttributeUsageAttribute;
typedef struct t_IL2X_CoreLib_System_BitConverter t_IL2X_CoreLib_System_BitConverter;
typedef struct t_IL2X_CoreLib_System_Buffer t_IL2X_CoreLib_System_Buffer;
typedef struct t_IL2X_CoreLib_System_Console t_IL2X_CoreLib_System_Console;
typedef struct t_IL2X_CoreLib_System_DateTime t_IL2X_CoreLib_System_DateTime;
typedef struct t_IL2X_CoreLib_System_Decimal t_IL2X_CoreLib_System_Decimal;
typedef struct t_IL2X_CoreLib_System_Delegate t_IL2X_CoreLib_System_Delegate;
typedef struct t_IL2X_CoreLib_System_Object t_IL2X_CoreLib_System_Object;
typedef struct t_IL2X_CoreLib_System_DllNotFoundException t_IL2X_CoreLib_System_DllNotFoundException;
typedef struct t_IL2X_CoreLib_System_Enum t_IL2X_CoreLib_System_Enum;
typedef struct t_IL2X_CoreLib_System_Environment t_IL2X_CoreLib_System_Environment;
typedef struct t_IL2X_CoreLib_System_EqualityComparer t_IL2X_CoreLib_System_EqualityComparer;
typedef struct t_IL2X_CoreLib_System_Exception t_IL2X_CoreLib_System_Exception;
typedef struct t_IL2X_CoreLib_System_FlagsAttribute t_IL2X_CoreLib_System_FlagsAttribute;
typedef struct t_IL2X_CoreLib_System_GC t_IL2X_CoreLib_System_GC;
typedef struct t_IL2X_CoreLib_System_Guid t_IL2X_CoreLib_System_Guid;
typedef struct t_IL2X_CoreLib_System_IDisposable t_IL2X_CoreLib_System_IDisposable;
typedef struct t_IL2X_CoreLib_System_IndexOutOfRangeException t_IL2X_CoreLib_System_IndexOutOfRangeException;
typedef struct t_IL2X_CoreLib_System_InvalidCastException t_IL2X_CoreLib_System_InvalidCastException;
typedef struct t_IL2X_CoreLib_System_Math t_IL2X_CoreLib_System_Math;
typedef struct t_IL2X_CoreLib_System_MathF t_IL2X_CoreLib_System_MathF;
typedef struct t_IL2X_CoreLib_System_MulticastDelegate t_IL2X_CoreLib_System_MulticastDelegate;
typedef struct t_IL2X_CoreLib_System_NotImplementedException t_IL2X_CoreLib_System_NotImplementedException;
typedef struct t_IL2X_CoreLib_System_NotSupportedException t_IL2X_CoreLib_System_NotSupportedException;
typedef struct t_IL2X_CoreLib_System_Number t_IL2X_CoreLib_System_Number;
typedef struct t_IL2X_CoreLib_System_ObsoleteAttribute t_IL2X_CoreLib_System_ObsoleteAttribute;
typedef struct t_IL2X_CoreLib_System_ParamArrayAttribute t_IL2X_CoreLib_System_ParamArrayAttribute;
typedef struct t_IL2X_CoreLib_System_Random t_IL2X_CoreLib_System_Random;
typedef struct t_IL2X_CoreLib_System_RuntimeType t_IL2X_CoreLib_System_RuntimeType;
typedef struct t_IL2X_CoreLib_System_RuntimeTypeHandle t_IL2X_CoreLib_System_RuntimeTypeHandle;
typedef struct t_IL2X_CoreLib_System_ThrowArgumentNullException t_IL2X_CoreLib_System_ThrowArgumentNullException;
typedef struct t_IL2X_CoreLib_System_Type t_IL2X_CoreLib_System_Type;
typedef struct t_IL2X_CoreLib_System_ValueType t_IL2X_CoreLib_System_ValueType;
typedef struct t_IL2X_CoreLib_System_Threading_Thread t_IL2X_CoreLib_System_Threading_Thread;
typedef struct t_IL2X_CoreLib_System_Text_Encoding t_IL2X_CoreLib_System_Text_Encoding;
typedef struct t_IL2X_CoreLib_System_Text_StandardEncoding t_IL2X_CoreLib_System_Text_StandardEncoding;
typedef struct t_IL2X_CoreLib_System_Text_StringBuilder t_IL2X_CoreLib_System_Text_StringBuilder;
typedef struct t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_DllImportAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_DllImportAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_Marshal t_IL2X_CoreLib_System_Runtime_InteropServices_Marshal;
typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_OutAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_OutAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute;
typedef struct t_IL2X_CoreLib_System_Runtime_CompilerServices_RuntimeHelpers t_IL2X_CoreLib_System_Runtime_CompilerServices_RuntimeHelpers;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyCompanyAttribute t_IL2X_CoreLib_System_Reflection_AssemblyCompanyAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyDelaySignAttribute t_IL2X_CoreLib_System_Reflection_AssemblyDelaySignAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyFileVersionAttribute t_IL2X_CoreLib_System_Reflection_AssemblyFileVersionAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyProductAttribute t_IL2X_CoreLib_System_Reflection_AssemblyProductAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute;
typedef struct t_IL2X_CoreLib_System_Reflection_DefaultMemberAttribute t_IL2X_CoreLib_System_Reflection_DefaultMemberAttribute;
typedef struct t_IL2X_CoreLib_System_IO_File t_IL2X_CoreLib_System_IO_File;
typedef struct t_IL2X_CoreLib_System_IO_FileNotFoundException t_IL2X_CoreLib_System_IO_FileNotFoundException;
typedef struct t_IL2X_CoreLib_System_IO_IOException t_IL2X_CoreLib_System_IO_IOException;
typedef struct t_IL2X_CoreLib_System_IO_Path t_IL2X_CoreLib_System_IO_Path;
typedef struct t_IL2X_CoreLib_System_Diagnostics_Debug t_IL2X_CoreLib_System_Diagnostics_Debug;
typedef struct t_IL2X_CoreLib_System_Collections_IEnumerable t_IL2X_CoreLib_System_Collections_IEnumerable;
typedef struct t_IL2X_CoreLib_System_Collections_IEnumerator t_IL2X_CoreLib_System_Collections_IEnumerator;

/* === Native Types === */
#include <stdint.h>
#define t_IL2X_CoreLib_System_Int32 int32_t
#define t_IL2X_CoreLib_System_Char uint16_t
#define t_IL2X_CoreLib_System_Boolean uint8_t
#define t_IL2X_CoreLib_System_Byte uint8_t
#define t_IL2X_CoreLib_System_IntPtr intptr_t
#define t_IL2X_CoreLib_System_Double double
#define t_IL2X_CoreLib_System_Int16 int16_t
#define t_IL2X_CoreLib_System_Int64 int64_t
#define t_IL2X_CoreLib_System_UInt32 uint32_t
#define t_IL2X_CoreLib_System_SByte int8_t
#define t_IL2X_CoreLib_System_Single float
#define t_IL2X_CoreLib_System_UInt16 uint16_t
#define t_IL2X_CoreLib_System_UInt64 uint64_t
#define t_IL2X_CoreLib_System_UIntPtr intptr_t

/* === Enums === */
#define t_IL2X_CoreLib_IL2X_NativeTarget t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_IL2X_NativeStringType t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_AttributeTargets t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_Runtime_InteropServices_LayoutKind t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedType t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplOptions t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_Reflection_MethodImplAttributes t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_IO_FileAccess t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_IO_FileMode t_IL2X_CoreLib_System_Int32
#define t_IL2X_CoreLib_System_IO_FileShare t_IL2X_CoreLib_System_Int32

/* === RuntimeTypeBase === */
typedef struct IL2X_RuntimeTypeBase IL2X_RuntimeTypeBase;
struct IL2X_RuntimeTypeBase
{
	t_IL2X_CoreLib_System_Type* Type;
	// TODO: string ptr to Name
	// TODO: string ptr to FullName
};

#include "il2x_builtins.h"
