#pragma once
#include "Microsoft_CodeAnalysis_EmbeddedAttribute.h"

#include "System_Attribute.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute__ctor_0(t_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute* self);

typedef struct rt_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute rt_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute;
struct rt_IL2X_CoreLib_Microsoft_CodeAnalysis_EmbeddedAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
