#pragma once
#include "__ForwardDeclares.h"
#include "System_Runtime_InteropServices_CallingConvention.h"
#include "System_Void.h"

typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_DllImportAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_DllImportAttribute;
struct t_IL2X_CoreLib_System_Runtime_InteropServices_DllImportAttribute
{
	void* RuntimeType;
	t_IL2X_CoreLib_System_String* f__Value_k__BackingField;
	t_IL2X_CoreLib_System_String* f_EntryPoint;
	t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention f_CallingConvention;
};
