#pragma once
#include "System_Reflection_AssemblyConfigurationAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute* self, t_IL2X_CoreLib_System_String* p_configuration);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute_get_Configuration_0(t_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyConfigurationAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
