#pragma once
#include "System_Runtime_CompilerServices_ExtensionAttribute.h"

#include "System_Attribute.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute rt_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute;
struct rt_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
