#pragma once
#include "System_Reflection_AssemblyKeyFileAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute* self, t_IL2X_CoreLib_System_String* p_keyFile);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute_get_KeyFile_0(t_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyKeyFileAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
