#include "System_Runtime_InteropServices_StructLayoutAttribute_Methods.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self, t_IL2X_CoreLib_System_Runtime_InteropServices_LayoutKind p_layoutKind)
{
	t_IL2X_CoreLib_System_Attribute__ctor_0(self);
	self->f__Value_k__BackingField = p_layoutKind;
	return;
}

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute__ctor_1(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self, t_IL2X_CoreLib_System_Int16 p_layoutKind)
{
	t_IL2X_CoreLib_System_Attribute__ctor_0(self);
	self->f__Value_k__BackingField = p_layoutKind;
	return;
}

t_IL2X_CoreLib_System_Runtime_InteropServices_LayoutKind t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute_get_Value_0(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self)
{
	return self->f__Value_k__BackingField;
}
