#pragma once
#include "System_Reflection_AssemblyDescriptionAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute* self, t_IL2X_CoreLib_System_String* p_description);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute_get_Description_0(t_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyDescriptionAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
