#pragma once
#include "System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute.h"

#include "System_Attribute.h"
#include "System_Runtime_InteropServices_CallingConvention.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute_get_CallingConvention_0(t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute* self);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute* self, t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention p_callingConvention);

typedef struct rt_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute rt_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute;
struct rt_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
