#include "System_IO_FileNotFoundException_Methods.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_IO_FileNotFoundException__ctor_0(t_IL2X_CoreLib_System_IO_FileNotFoundException* self)
{
	t_IL2X_CoreLib_System_Exception__ctor_0(self);
	return;
}

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_IO_FileNotFoundException__ctor_1(t_IL2X_CoreLib_System_IO_FileNotFoundException* self, t_IL2X_CoreLib_System_String* p_message)
{
	t_IL2X_CoreLib_System_Exception__ctor_1(p_message, self);
	return;
}
