#pragma once
#include "System_Reflection_AssemblyTrademarkAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute* self, t_IL2X_CoreLib_System_String* p_trademark);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute_get_Trademark_0(t_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyTrademarkAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
