#include "System_Runtime_CompilerServices_ExtensionAttribute_Methods.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_CompilerServices_ExtensionAttribute* self)
{
	t_IL2X_CoreLib_System_Attribute__ctor_0(self);
	return;
}
