#include "System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute_Methods.h"

t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute_get_CallingConvention_0(t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute* self)
{
	return self->f__CallingConvention_k__BackingField;
}

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute* self, t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention p_callingConvention)
{
	t_IL2X_CoreLib_System_Attribute__ctor_0(self);
	self->f__CallingConvention_k__BackingField = p_callingConvention;
	return;
}
