#pragma once
#include "System_Runtime_InteropServices_StructLayoutAttribute.h"

#include "System_Attribute.h"
#include "System_Runtime_InteropServices_LayoutKind.h"
#include "System_Int32.h"
#include "System_Void.h"
#include "System_Int16.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self, t_IL2X_CoreLib_System_Runtime_InteropServices_LayoutKind p_layoutKind);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute__ctor_1(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self, t_IL2X_CoreLib_System_Int16 p_layoutKind);
t_IL2X_CoreLib_System_Runtime_InteropServices_LayoutKind t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute_get_Value_0(t_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute rt_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute;
struct rt_IL2X_CoreLib_System_Runtime_InteropServices_StructLayoutAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
