#pragma once
#include "System_ArgumentOutOfRangeException.h"

#include "System_Exception.h"
#include "System_Void.h"
#include "System_String.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_ArgumentOutOfRangeException__ctor_0(t_IL2X_CoreLib_System_ArgumentOutOfRangeException* self);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_ArgumentOutOfRangeException__ctor_1(t_IL2X_CoreLib_System_ArgumentOutOfRangeException* self, t_IL2X_CoreLib_System_String* p_message);

typedef struct rt_IL2X_CoreLib_System_ArgumentOutOfRangeException rt_IL2X_CoreLib_System_ArgumentOutOfRangeException;
struct rt_IL2X_CoreLib_System_ArgumentOutOfRangeException
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
