#pragma once
#include "System_Reflection_AssemblyInformationalVersionAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute* self, t_IL2X_CoreLib_System_String* p_informationalVersion);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute_get_InformationalVersion_0(t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
