#pragma once
#include "System_Reflection_AssemblyCopyrightAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute* self, t_IL2X_CoreLib_System_String* p_copyright);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute_get_Copyright_0(t_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyCopyrightAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
