#include "System_Collections_IEnumerable_Methods.h"

t_IL2X_CoreLib_System_Collections_IEnumerator* t_IL2X_CoreLib_System_Collections_IEnumerable_GetEnumerator_0(t_IL2X_CoreLib_System_Collections_IEnumerable* self)
{
}
