#pragma once
#include "System_Runtime_Versioning_TargetFrameworkAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute* self, t_IL2X_CoreLib_System_String* p_frameworkName);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute_get_FrameworkDisplayName_0(t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute* self);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute_set_FrameworkDisplayName_0(t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute* self, t_IL2X_CoreLib_System_String* p_value);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute_get_FrameworkName_0(t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute* self);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute_set_FrameworkName_0(t_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute* self, t_IL2X_CoreLib_System_String* p_value);

typedef struct rt_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute rt_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute;
struct rt_IL2X_CoreLib_System_Runtime_Versioning_TargetFrameworkAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
