#pragma once
#include "System_Reflection_AssemblyCultureAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute* self, t_IL2X_CoreLib_System_String* p_culture);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute_get_Culture_0(t_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyCultureAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
