#pragma once
#include "__ForwardDeclares.h"
#include "System_Runtime_InteropServices_CallingConvention.h"
#include "System_Void.h"

typedef struct t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute;
struct t_IL2X_CoreLib_System_Runtime_InteropServices_UnmanagedFunctionPointerAttribute
{
	void* RuntimeType;
	t_IL2X_CoreLib_System_Runtime_InteropServices_CallingConvention f__CallingConvention_k__BackingField;
};
