#include "System_Runtime_InteropServices_OutAttribute_Methods.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_InteropServices_OutAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_InteropServices_OutAttribute* self)
{
	t_IL2X_CoreLib_System_Attribute__ctor_0(self);
	return;
}
