#pragma once
#include "System_NotImplementedException.h"

#include "System_Exception.h"
#include "System_Void.h"
#include "System_String.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_NotImplementedException__ctor_0(t_IL2X_CoreLib_System_NotImplementedException* self);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_NotImplementedException__ctor_1(t_IL2X_CoreLib_System_NotImplementedException* self, t_IL2X_CoreLib_System_String* p_message);

typedef struct rt_IL2X_CoreLib_System_NotImplementedException rt_IL2X_CoreLib_System_NotImplementedException;
struct rt_IL2X_CoreLib_System_NotImplementedException
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
