#pragma once
#include "System_Reflection_AssemblyVersionAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute* self, t_IL2X_CoreLib_System_String* p_version);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute_get_Version_0(t_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyVersionAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
