#pragma once
#include "__ForwardDeclares.h"
#include "System_Void.h"

typedef struct t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute;
struct t_IL2X_CoreLib_System_Reflection_AssemblyInformationalVersionAttribute
{
	void* RuntimeType;
	t_IL2X_CoreLib_System_String* f__informationalVersion;
};
