#pragma once
#include "System_Runtime_CompilerServices_MethodImplAttribute.h"

#include "System_Attribute.h"
#include "System_Runtime_CompilerServices_MethodImplOptions.h"
#include "System_Void.h"
#include "System_Int16.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute__ctor_0(t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute* self, t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplOptions p_methodImplOptions);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute__ctor_1(t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute* self, t_IL2X_CoreLib_System_Int16 p_value);
t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute__ctor_2(t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute* self);
t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplOptions t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute_get_Value_0(t_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute rt_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute;
struct rt_IL2X_CoreLib_System_Runtime_CompilerServices_MethodImplAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
