#pragma once
#include "System_Reflection_AssemblyTitleAttribute.h"

#include "System_Attribute.h"
#include "System_String.h"
#include "System_Void.h"

t_IL2X_CoreLib_System_Void t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute__ctor_0(t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute* self, t_IL2X_CoreLib_System_String* p_title);
t_IL2X_CoreLib_System_String* t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute_get_Title_0(t_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute* self);

typedef struct rt_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute rt_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute;
struct rt_IL2X_CoreLib_System_Reflection_AssemblyTitleAttribute
{
	IL2X_RuntimeTypeBase RuntimeTypeBase;
};
